### ISSUE TITLE
Issue: weekly view does not have "difference" of placemente 

### ISSUE THREAD

**Issue by martaEventix** [StefGeraets/poolscoreboard#19]
daily:
![image](https://github.com/StefGeraets/poolscoreboard/assets/100291390/6fe58b85-2287-4b05-935f-60786465ee46)

weekly:
![image](https://github.com/StefGeraets/poolscoreboard/assets/100291390/c3582cde-7dac-4772-b4c2-f746ef15a846)

**Comment by StefGeraets** [comment]
It has, this was, by the time you where checking this and seeing this issue, not applicable due to test data per week score
